/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.harshit.qcalc;

import com.harshit.qcalc.StandardCalculator;

public class App {
//    public String getGreeting() {
//        return "Hello world";
//    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        StandardCalculator.getVersion();
        StandardCalculator calc= new StandardCalculator();
        calc.divide(2,2);
        calc.getResult();
        calc.printResult();
        // LogicCalculator lcalc= new LogicCalculator();
        // lcalc.AND(8,2);
        // lcalc.printResult();
        // ScientificCalculator scalc= new ScientificCalculator();
        // scalc.sqrt(25);
        // scalc.printResult();
    }
}
